version: '3'
services:
  navigation:
    build:
      context: .
      dockerfile: Dockerfile
    image: navigation:latest
    container_name: navigation
    restart: always
    ports:
      - 8080:8080
    volumes:
    - ./db.sqlite3:/usr/local/web/db.sqlite3
