version: '3'
services:
  navigation:
    image: navigation:latest
    container_name: navigation
    restart: always
    ports:
      - 8000:8080
    volumes:
    - ./db.sqlite3:/usr/local/web/db.sqlite3
