version: '3'
services:
  navigation:
    image: twoyang0917/navigation:1.1
    container_name: navigation
    restart: always
    ports:
      - 8080:8080
    environment:
      - DBHOST=127.0.0.1
      - DBPORT=3306
      - DBNAME=navigation
      - DBUSER=navigation
      - DBPASSWORD=navigation
